/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */
/** Simple brace matcher. */
package good.love.music.comu;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MELODY = 5;
  /** RegularExpression Id. */
  int BEAT = 6;
  /** RegularExpression Id. */
  int BASS = 7;
  /** RegularExpression Id. */
  int PIANO = 8;
  /** RegularExpression Id. */
  int DRUM = 9;
  /** RegularExpression Id. */
  int GUITARNOTE = 10;
  /** RegularExpression Id. */
  int GUITARCODE = 11;
  /** RegularExpression Id. */
  int REVERB = 12;
  /** RegularExpression Id. */
  int DELAY = 13;
  /** RegularExpression Id. */
  int LOWFILTER = 14;
  /** RegularExpression Id. */
  int HIGHFILTER = 15;
  /** RegularExpression Id. */
  int TEMPO = 16;
  /** RegularExpression Id. */
  int BPM = 17;
  /** RegularExpression Id. */
  int DO = 18;
  /** RegularExpression Id. */
  int LOCATION = 19;
  /** RegularExpression Id. */
  int NUMBER = 20;
  /** RegularExpression Id. */
  int DIGIT = 21;
  /** RegularExpression Id. */
  int INS = 22;
  /** RegularExpression Id. */
  int SETNOTE = 23;
  /** RegularExpression Id. */
  int NOTE = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"melody\"",
    "\"beat\"",
    "\"bass\"",
    "\"piano\"",
    "\"drum\"",
    "\"guitarcode\"",
    "\"guitarnote\"",
    "\"reverb\"",
    "\"delay\"",
    "\"low\"",
    "\"high\"",
    "\"tempo\"",
    "\"bpm\"",
    "\"do\"",
    "\"location\"",
    "<NUMBER>",
    "<DIGIT>",
    "\"ins\"",
    "\"note\"",
    "<NOTE>",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\",\"",
    "\");\"",
  };

}
