/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */
/** Simple brace matcher. */
package good.love.music.comu;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TEMPO = 5;
  /** RegularExpression Id. */
  int BPM = 6;
  /** RegularExpression Id. */
  int DO = 7;
  /** RegularExpression Id. */
  int LOCATION = 8;
  /** RegularExpression Id. */
  int INS = 9;
  /** RegularExpression Id. */
  int LOOP = 10;
  /** RegularExpression Id. */
  int EFFECT = 11;
  /** RegularExpression Id. */
  int SETNOTE = 12;
  /** RegularExpression Id. */
  int NUMBER = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int ALPHA = 15;
  /** RegularExpression Id. */
  int NOTE = 16;
  /** RegularExpression Id. */
  int WORD = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"tempo\"",
    "\"bpm\"",
    "\"do\"",
    "\"location\"",
    "\"ins\"",
    "\"loop\"",
    "<EFFECT>",
    "\"note\"",
    "<NUMBER>",
    "<DIGIT>",
    "<ALPHA>",
    "<NOTE>",
    "<WORD>",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\",\"",
    "\");\"",
  };

}
